kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cedar-cluster
# Must use kind >= v0.24.0 with K8s 1.31+
# for the following feature gates
featureGates:
  AuthorizeNodeWithSelectors: true
  AuthorizeWithSelectors: true
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta4
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        - name: "authorization-config"
          value: "/cedar-authorizer/authorization-config.yaml"
        - name: "audit-policy-file"
          value: "/cedar-authorizer/audit-policy.yaml"
        - name: "audit-log-path"
          value: "/cedar-authorizer/logs/kube-apiserver-audit.log"
        - name: "audit-log-maxsize"
          value: "50"
        - name: "audit-log-maxbackup"
          value: "1"
      extraVolumes:
      - hostPath: /cedar-authorizer
        mountPath: /cedar-authorizer
        name: api-server-cedar-authorizer-files
nodes:
  - role: control-plane
    image: cedar-kind-node:latest
    extraMounts:
      - hostPath: "./mount"
        containerPath: "/cedar-authorizer"
      - hostPath: "./manifests/cedar-authorization-webhook.yaml"
        containerPath: "/etc/kubernetes/manifests/cedar-authorization-webhook.yaml"
